# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tweetreader.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tweetreader.proto',
  package='tweetreader',
  syntax='proto3',
  serialized_options=b'\n\007ex.grpc\242\002\003HSW',
  serialized_pb=b'\n\x11tweetreader.proto\x12\x0btweetreader\"C\n\x05Tweet\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\"\x0e\n\x0cTweetRequest2M\n\x0bTweetReader\x12>\n\tgetTweets\x12\x19.tweetreader.TweetRequest\x1a\x12.tweetreader.Tweet\"\x00\x30\x01\x42\x0f\n\x07\x65x.grpc\xa2\x02\x03HSWb\x06proto3'
)




_TWEET = _descriptor.Descriptor(
  name='Tweet',
  full_name='tweetreader.Tweet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='tweetreader.Tweet.target', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='tweetreader.Tweet.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='tweetreader.Tweet.username', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='tweetreader.Tweet.id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=101,
)


_TWEETREQUEST = _descriptor.Descriptor(
  name='TweetRequest',
  full_name='tweetreader.TweetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['Tweet'] = _TWEET
DESCRIPTOR.message_types_by_name['TweetRequest'] = _TWEETREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tweet = _reflection.GeneratedProtocolMessageType('Tweet', (_message.Message,), {
  'DESCRIPTOR' : _TWEET,
  '__module__' : 'tweetreader_pb2'
  # @@protoc_insertion_point(class_scope:tweetreader.Tweet)
  })
_sym_db.RegisterMessage(Tweet)

TweetRequest = _reflection.GeneratedProtocolMessageType('TweetRequest', (_message.Message,), {
  'DESCRIPTOR' : _TWEETREQUEST,
  '__module__' : 'tweetreader_pb2'
  # @@protoc_insertion_point(class_scope:tweetreader.TweetRequest)
  })
_sym_db.RegisterMessage(TweetRequest)


DESCRIPTOR._options = None

_TWEETREADER = _descriptor.ServiceDescriptor(
  name='TweetReader',
  full_name='tweetreader.TweetReader',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=119,
  serialized_end=196,
  methods=[
  _descriptor.MethodDescriptor(
    name='getTweets',
    full_name='tweetreader.TweetReader.getTweets',
    index=0,
    containing_service=None,
    input_type=_TWEETREQUEST,
    output_type=_TWEET,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TWEETREADER)

DESCRIPTOR.services_by_name['TweetReader'] = _TWEETREADER

# @@protoc_insertion_point(module_scope)
