# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tweetreader_pb2 as tweetreader__pb2


class TweetReaderStub(object):
  """Tweet reader service docs
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getTweets = channel.unary_stream(
        '/tweetreader.TweetReader/getTweets',
        request_serializer=tweetreader__pb2.TweetRequest.SerializeToString,
        response_deserializer=tweetreader__pb2.Tweet.FromString,
        )


class TweetReaderServicer(object):
  """Tweet reader service docs
  """

  def getTweets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TweetReaderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getTweets': grpc.unary_stream_rpc_method_handler(
          servicer.getTweets,
          request_deserializer=tweetreader__pb2.TweetRequest.FromString,
          response_serializer=tweetreader__pb2.Tweet.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tweetreader.TweetReader', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
