apiVersion: v1
kind: Service
metadata:
  name: metrics-webpage
  labels:
    app: metrics-webpage
spec:
  selector:
    app: metrics-webpage
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30000
      protocol: TCP